name: RCM2
main: com.sinius15.rcm.Main
author: Sinius15
website: http://dev.bukkit.org/bukkit-plugins/rollercoaster-manager/
version: 1.50a
commands:
   rcm:
       description: base command.
       usage: "Do /rcm help for all the available commands."
